[package]
name = "ifcloud-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
tokio = { version = "1", features = ["full"] }
redis = { version = "0.27.0", features = ["tokio-comp"] }
async-trait = "0.1.82"
fred = "9.2.1"
thiserror = "1.0.63"
