services:
  ifcloud-storage:
    build:
      context: .
      dockerfile: Dockerfile
    image: ifcloud-storage
    container_name: ifcloud-storage
    ports:
      - "3000:3000"
      - "3001:3001"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - ifcloud-network
    depends_on:
      - token
      - session
      - rabbit  

  token:
    container_name: token
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6666:6379"
    networks:
      - ifcloud-network

  session:
    container_name: session
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - ifcloud-network

  rabbit:
    container_name: rabbit
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    # volumes:
    #   - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
    #   - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
    #   - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ifcloud-network
    # env_file:
    #   - rabbit.env

networks:
  ifcloud-network:
    name: ifcloud-network
