[package]
name = "runner"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
tokio = { version = "1.40.0", features = ["full"] }
file-uploader = { path = "../file-uploader" }
storage-manager = { path = "../storage-manager" }
